baseURL = "http://leonardoborges.com/"
languageCode = "en-us"
title = "Leonardo Borges"
theme = "ananke"
disqusShortname = "leonardoborges"
googleAnalytics = "UA-2811271-1"

# SectionPagesMenu = "main"

[markup.goldmark.renderer]
unsafe= true

[menu]

  [[menu.main]]
    identifier = "writings"
    name = "Posts"
    title = "All posts"
    url = "/writings/"

  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"    

  [[menu.main]]
    identifier = "books"
    name = "Books"
    title = "Books"
    url = "/books/"

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    title = "Tags"
    url = "/tags/"

  [[menu.main]]
    identifier = "talks"
    name = "Projects & Talks"
    title = "Projects & Talks"
    url = "/talks/"    


[params]
  favicon = "images/favicon.png"
  description = "Code. Leadership. AI."
  title = "Code. Leadership. AI."
  twitter = "https://twitter.com/leonardo_borges"
  github = "https://github.com/leonardoborges"
  linkedin = "https://www.linkedin.com/in/leonardoborges/"
  stackoverflow = "https://stackoverflow.com/users/910811/leonardoborges"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  # background_color_class = "bg-black"
  featured_image = "/images/wanaka_tree.jpg"
  # recent_posts_number = 2
